name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
  DOCKER_REGISTRY: cnbzbwxdqyt2
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v2.2.1
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast

  build_image:
    needs: [lint]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: "icn.ocir.io"
        # Username used to log against the Docker registry
        username: ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASS }}
        # Log out from the Docker registry at the end of a job
        logout: true # optional, default is true

    - name: Build and tag image
      run: docker build -t "icn.ocir.io/${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:latest" .

    - name: Push to OCIR image registry
      run: docker push icn.ocir.io/${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:latest

  test_image:
    needs: [build_image]
    runs-on: ubuntu-18.04
    steps:
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: "icn.ocir.io"
        # Username used to log against the Docker registry
        username: ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASS }}
        # Log out from the Docker registry at the end of a job
        logout: true # optional, default is true

    - name: Run unit tests in container
      run: docker run "icn.ocir.io/${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:latest" -m unittest --verbose --failfast
